//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratings.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RatingsContext : DbContext
    {
        public RatingsContext()
            : base("name=RatingsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FullTimeFaculty> FullTimeFaculties { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<SchoolsWithOneTwoAccreditationLevel> SchoolsWithOneTwoAccreditationLevels { get; set; }
        public virtual DbSet<UniversityStructureStatistic> UniversityStructureStatistics { get; set; }
    }
}
