//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ratings.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityStructureStatistic
    {
        public System.Guid FacultyId { get; set; }
        public Nullable<int> NoOfDepartments { get; set; }
        public Nullable<int> NoOfDepartmentsHeadedByDoctorsProfessorsFullTime { get; set; }
        public Nullable<int> NoOfReleasingDepartments { get; set; }
        public Nullable<int> NoOfReleasingDepartmentsHeadedByDoctorsProfessorsFullTime { get; set; }
        public Nullable<int> NoOfSmallDepartmentsWithLessThanFiveTeachers { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
